baseURL = 'https://daidaiwoma.github.io/'
languageCode = 'zh-cn'
title = 'Gopher.log'
theme = 'PaperMod'

[params]
    defaultTheme = "dark"
    # 强制开启显示文章全文摘要（可选）
    showFullContents = false
    displayFullPostContent = false

    [params.homeInfoParams]
        Title = "Hi, I'm daidaiwoma."
        Content = "专注于 Go 语言后端与 AI 应用开发。正在执行“延长周末”计划。"

# 导航栏配置
[[menu.main]]
    name = "~/posts"
    url = "/posts/"
    weight = 10
[[menu.main]]
    name = "~/projects"
    url = "/projects/"
    weight = 20
